version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.21.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.0
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.35.1
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.4.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
    - 7.13.15
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.18
    - 8.1.0
  - dependency-name: "@types/bootstrap"
    versions:
    - 5.0.4
    - 5.0.5
    - 5.0.7
    - 5.0.8
    - 5.0.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.9
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.2.1
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: less
    versions:
    - 4.1.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - rullzer
  - icewind1991
  - juliushaertl
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a, < 10"
  - dependency-name: symfony/event-dispatcher
    versions:
    - ">= 5.a, < 6"
  - dependency-name: psalm/phar
    versions:
    - 4.5.1
    - 4.5.2
    - 4.6.0
    - 4.6.1
    - 4.6.3
  - dependency-name: sabre/dav
    versions:
    - 4.1.5
